### PR TITLE
Added download file feature

### PR DESCRIPTION
**Pull request by leophys**
Now there is the possibility to download files via coffer.
The feature is very simple right now: the file is saved in the current directory of the client with the name of the file offered. In future there should be the possibility to choose the file name.

I tried this feature only locally on my machine. More testing is needed.

### CODE REVIEW

**Comment by boyska** [comment]
very good. Are you sure that the file name is the same as the file offered? (need to test)

**Comment by leophys** [comment]
I tested this feature with two different *nix machines in LAN.
It works in the case
`
server$ coffer send <file>
`
`
client$ coffer get
`

It **doesn't** work in the case

`
server$ coffer send --one <file>
`
`
client$ coffer get
`

With error 404 (client side), and with a a strange behavior on server
side:

`
<client ip> - - [2015-05-13 01:50:14] "GET /offers HTTP/1.1" 200 164 0.002033
`
`
<client ip> - - [2015-05-13 01:50:15] "GET /offers/<file> HTTP/1.1" 200 173313 0.055152
`
`
<client ip> - - [2015-05-13 01:50:15] "GET /offers/<file> HTTP/1.0" 404 361 0.002738
`

Dunno why.

**Comment by boyska** [comment]
Thanks for testing it yourself. The reason is clearly stated in the `--one` option: it will allow only one download per file. You are doing TWO downloads. This is wrong.

The code is quite clear in that regard:

``` python
   response = client.dl_offer(url, args.password)
    if args.cat:
         sys.stdout.write(response.text)
     else:
            save_file(url)
```

so you are downloading once with `dl_offer` and twice with `save_file`.
You should just save the response instead.

**Comment by boyska** [comment]
11317b5089e solves the `--one` issue (which is also a slowness issue since otherwise every file is downloaded two times)

**Pull request merged**
